# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 238058326ebf37cc7cd4b8c00429aa703c526e680d8a8bdb3d0d94b28b43ab2ae54d5993f1711e765bb4547a36bbf0468c1808ad8caaa8fecef436ea9a28ebcc

test:
  secret_key_base: 78b9e38dbd47034cf1489e41977adc1ec86cf711cdeb15fa77af7004e48b4529ef8692b713f24f856999ef0720640aeaf63a8b89a46b2d46b65340f8afc75723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
